<a href="https://colab.research.google.com/github/Saransh6045/Machine_Learning/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

Creating the matrix

In [22]:
mat_1 = np.asarray([[1,2],[3,4],[5,6]])
print(mat_1)

[[1 2]
 [3 4]
 [5 6]]


In [23]:
mat_1.shape

(3, 2)

Creating a matrices with random value

In [24]:
random_matrix = np.random.rand(2,3)
print(random_matrix)

[[0.84451326 0.68125634 0.49194104]
 [0.76999623 0.57391488 0.16105508]]


Creating a matrices with random integer

In [25]:
random_integer_matrix = np.random.randint(100, size=(3,3))
print(random_integer_matrix)

[[59 59 68]
 [70 65  0]
 [14 46 78]]


Creating matrices with all the values as 1

In [26]:
mat_3 = np.ones((3,4))
print(mat_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
mat_3 = np.ones((3,4), dtype=int)
print(mat_3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Null Matrix or Zero Matrix

In [28]:
null_matrix = np.zeros((3,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
null_matrix = np.zeros((3,4), dtype=int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Identity Matrix

In [30]:
ident_mat = np.eye(3)
print(ident_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of a Matrix

In [31]:
mat_random = np.random.randint(100, size=(4,5))
print(mat_random)

[[29 80 53 60 17]
 [56 57 31 37 77]
 [61 57 70 18 23]
 [85 84 25 93 65]]


In [32]:
transposed_mat = np.transpose(mat_random)
print(transposed_mat)

[[29 56 61 85]
 [80 57 57 84]
 [53 31 70 25]
 [60 37 18 93]
 [17 77 23 65]]


#Matrix Operations

In [33]:
mat_1 = np.array([[1,2],[3,4]])
mat_2 = np.array([[5,6],[7,8]])

In [34]:
print(mat_1)
print(mat_2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


Matrix Addition

In [35]:
sum = mat_1 + mat_2
print(sum)

[[ 6  8]
 [10 12]]


In [36]:
#Another Way
sum = np.add(mat_1,mat_2)
print(sum)

[[ 6  8]
 [10 12]]


Matric Subtraction

In [37]:
diff = mat_1 - mat_2
print(diff)

[[-4 -4]
 [-4 -4]]


In [38]:
#or


diff = np.subtract(mat_1,mat_2)
print(diff)

[[-4 -4]
 [-4 -4]]


Multiplying a Matrix by a Scalar

In [39]:
mat = np.random.randint(20, size=(3,3))
print(mat)

[[13  6  7]
 [ 2  8  0]
 [10  1  6]]


In [40]:
x = 2
mul = mat * x
print(mul)

[[26 12 14]
 [ 4 16  0]
 [20  2 12]]


In [41]:
#or

mul = np.multiply(mat,x)
print(mul)

[[26 12 14]
 [ 4 16  0]
 [20  2 12]]


Multiplying Two Matrices

In [43]:
matrix_1 = np.random.randint(10,size=(2,3))
matrix_2 = np.random.randint(10,size=(3,2))

print(matrix_1)

[[4 8 0]
 [1 1 8]]


In [44]:
print(matrix_2)

[[0 1]
 [9 3]
 [2 6]]


In [46]:
multiplication = np.dot(matrix_1,matrix_2)
print(multiplication)

[[72 28]
 [25 52]]


Element Wise Matrix Multiplication

In [48]:
matr_1 = np.random.randint(10,size=(3,3))
matr_2 = np.random.randint(10,size=(3,3))

In [49]:
print(matr_1)

[[0 9 5]
 [3 8 0]
 [6 6 4]]


In [50]:
print(matr_2)

[[4 7 9]
 [5 3 9]
 [3 3 2]]


In [51]:
ele_mul = np.multiply(matr_1,matr_2)
print(ele_mul)

[[ 0 63 45]
 [15 24  0]
 [18 18  8]]
