<a href="https://colab.research.google.com/github/Saransh6045/Machine_Learning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np


List vs NumPy

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
lst1 = [i for i in range(10000)]

start_time = process_time()

lst2 = [i+5 for i in lst1]

end_time = process_time();

print(end_time - start_time)

0.0006725220000003418


Time taken by np array

In [ ]:
np_arr1 = np.array([i for i in range(10000)])

start_time = process_time()

np_arr1 += 5

end_time = process_time();

print(end_time - start_time)

0.0002108899999999636


NumPy arrays

In [ ]:
np_arr = np.array([1,2,3,4])
print(np_arr)
type(np_arr)

[1 2 3 4]


numpy.ndarray

In [ ]:
#1-d array
np_arr = np.array([1,2,3,4,5])
print(np_arr)
np_arr.shape


[1 2 3 4 5]


(5,)

In [ ]:
#shape
a = np.array([(1,2,3,4), (5,6,7,8), (9,10,11,12)])
a.shape
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#dtype
a = np.array([(1,2,3,4), (5,6,7,8), (9,10,11,12)],dtype=float)
print(a)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


Initial Placeholders in NumPy arrays

In [ ]:
#Creating a numpy array of zeroes
a = np.zeros((3,4))
print(a)

#All ones
b = np.ones((4,5))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Creating a matrix with specific intitial placeholder value
a = np.full((2,3), 6)
print(a)

[[6 6 6]
 [6 6 6]]


In [ ]:
#Creating an Identity Matrix
a = np.eye(5)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#Creating a numpy array with random values
a = np.random.random((3,4))
print(a)

[[0.40259065 0.10162105 0.82697841 0.6782314 ]
 [0.44442442 0.74727987 0.567117   0.82908634]
 [0.03056559 0.38453781 0.45728393 0.67465267]]


In [ ]:
#Creating a numpy array with random integer values within a specificn range
c = np.random.randint(1,100,(2,3))
print(c)

[[64 10 56]
 [51 49 62]]


In [ ]:
#Array of evenly spaced values --> specifying the number of values required
a = np.linspace(10,30,8)
print(a)

[10.         12.85714286 15.71428571 18.57142857 21.42857143 24.28571429
 27.14285714 30.        ]


In [ ]:
#Array of evenly spaced values --> specifying the number of steps
a = np.arange(10,30,5)
print(a)

[10 15 20 25]


In [ ]:
#Convert the list to a numpy array
lst = [1,2,3,4]
a = np.asarray(lst)
print(a)

[1 2 3 4]


Analysing a numpy array

In [ ]:
c = np.random.randint(1,100,(3,4))
print(c)

[[64 28 26 31]
 [10 51 44  2]
 [ 4 48 86 84]]


In [ ]:
#array dimension
c.shape

(3, 4)

In [ ]:
#number of dimensions
print(c.ndim)

2


In [ ]:
#number of elements in an array
print(c.size)

12


In [ ]:
#checking the datatypes of the values in an array

print(c.dtype)


int64


Mathematical Operations on a np array


In [ ]:
a = np.random.randint(1,10,(2,3))
b = np.random.randint(1,10,(2,3))
print(a)
print(b)

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[2 8 7]
 [3 6 9]]
[[8 2 1]
 [6 4 9]]
[[10 10  8]
 [ 9 10 18]]
[[-6  6  6]
 [-3  2  0]]
[[16 16  7]
 [18 24 81]]
[[0.25 4.   7.  ]
 [0.5  1.5  1.  ]]


Array Manipulation

In [ ]:
a = np.random.randint(1,10,(2,4))
print(a)
a.shape

[[5 3 3 6]
 [5 9 8 6]]


(2, 4)

In [ ]:
#Transpose
trans = np.transpose(a)
print(trans)

[[5 5]
 [3 9]
 [3 8]
 [6 6]]


In [ ]:
a = np.random.randint(1,10,(2,4))
print(a)

trans = a.T
print(trans)

[[6 8 8 7]
 [1 9 3 8]]
[[6 1]
 [8 9]
 [8 3]
 [7 8]]


In [ ]:
#reshaping an array
a = np.random.randint(1,10,(2,4))
print(a)

b = a.reshape(4,2)
print(b)

[[4 4 2 7]
 [1 7 8 8]]
[[4 4]
 [2 7]
 [1 7]
 [8 8]]
